baseURL = "https://blog.idontwannarock.dev/"
DefaultContentLanguage = "en"
languageCode = "en-us"
title = "Howard Tech Note"
copyright = "This website by Howard Wang is licensed under a Creative Common Attribution-ShareAlike 4.0 International License."
license = "CC BY 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0/"
theme = "diary"
canonifyURLs = true

# Google Analytics
[services]
  [services.googleAnalytics]
    id = "G-JP1V61PPMJ"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe = true

[params]
subtitle = "Share * Record * Program"
disqusShortname = "howard-tech-blog"
cloudflareToken = "69057f1b88b9492497f024d5a9bdc22e"
googleAnalytics = "G-JP1V61PPMJ"

[permalinks]
posts = "/:year/:month/:slug"
pages = "/:slug"

[taxonomies]
  tag = "tags"
  category = "categories"

[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1
[[menu.main]]
url = "/categories"
name = "Categories"
weight = 2
[[menu.main]]
url = "/tags"
name = "Tags"
weight = 3
#[[menu.main]]
#url = "/works"
#name = "My Works"
#sweight = 4
[[menu.main]]
url = "/about"
name = "About"
weight = 5
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 6
